### ISSUE TITLE
Question: How to create multiple data-builders

### ISSUE THREAD

**Issue by viduc** [buildotter/php-core#17]
Hi, thanks for your work.

I would know if its possible to create multiple data-builder. I would cut this file to have one by entity. I try to add require file to do this but dont work.

Thanks

**Comment by viduc** [comment]
I found.. i can create multiple file and declare them in composer

**Comment by brambaud** [comment]
Hi! Thanks for testing this library! 😁 

In case someone else has this question:

I assume the question is about the optional "functions' file" that the [Buildotter Maker Standalone](https://github.com/buildotter/php-maker-standalone) may create.
It is the same that we talk about in the readme in `buildotter/php-core`:

> For instance, we may have a file containing the following functions:
>
> ```php
> use App\Fixtures\Builder\ElephantBuilder;
> use App\Fixtures\Builder\TopicBuilder;
>
> function random(): \Faker\Generator
> {
>     return \Faker\Factory::create();
> }
>
> function anElephant(): ElephantBuilder
> {
>     return ElephantBuilder::new();
> }
>
 > // etc...
> ```
>

The documentation to configure composer to add php file that cannot be added using `classmap`, `psr-0` or the standard `psr-4` is here: https://getcomposer.org/doc/04-schema.md#files

```json
{
    "autoload": {
        "files": ["src/MyLibrary/functions.php"]
    }
}
```

PS: if you were using [Buildotter Maker Standalone](https://github.com/buildotter/php-maker-standalone) and this was not clear enough, I'm sorry about it!

**Comment by viduc** [comment]
Hi, thanks for your answer, yes i use the maker. No problems i was fond that we must add in composer the file.
Perhaps add process to do it automatically in maker?

in any case thank you for your work it's a very good initiative

**Comment by brambaud** [comment]
> Perhaps add process to do it automatically in maker?

It is something on my mind indeed 😁 
For the moment I have discarded it to focus on other features (like the bridge with Symfony) and the standalone maker already try to report this in the success message and with a note, see https://github.com/buildotter/php-maker-standalone-src/blob/6294abc5f00d52ba47fcea11b66dbc4c1da56988/src/Command/GenerateCommand.php#L214

The issue https://github.com/buildotter/php-maker-standalone-src/issues/25 has been created to make it track this.
